function transVolumeToFreesurferSpace(volume,FS_sub_path,sub_name,outpath,prefix,output_format,interpolation)
%cubic(B-Spline), trilin, nearest
if ~exist(outpath,'dir')
    mkdir(outpath);
end
system(['export LD_PRELOAD=/opt/software/glibc-2.14/lib/libc-2.14.so;'...
    'source /etc/profile;'...
    'tkregister2 --mov ' FS_sub_path '/' sub_name '/mri/rawavg.mgz --targ '...
    FS_sub_path '/' sub_name '/mri/orig.mgz --reg '...
    outpath '/' prefix '.register.dat --noedit --regheader']);

system(['mri_vol2vol --reg ' outpath '/' prefix '.register.dat '...
    '--mov ' volume ' --targ ' FS_sub_path '/' sub_name '/mri/T1.mgz  '...
    '--o ' outpath '/' prefix '.' output_format ' --interp ' interpolation]);